name: Tests

on: [push, workflow_dispatch]

permissions: {}
jobs:
  runPush:
    permissions:
      contents: write # for Update bundles

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Run unit tests and build JAR
      run: ./gradlew test desktop:dist
    - name: Upload desktop JARfile
      uses: actions/upload-artifact@v2
      with:
        name: Cursedustry (zipped)
        path: desktop/build/libs/Mindustry.jar
